from pydantic import BaseModel, Field


class Question(BaseModel):
    question: str = Field(..., description="The question to ask to user")


class QuestionsModel(BaseModel):
    explanation: str = Field(..., description="The explanation generated by agent")
    questions: list[Question] = Field(..., description="A list of questions generated by agent")


class Feature(BaseModel):
    feature: str = Field(..., description="The short description of feature")

class Resource(BaseModel):
    developer: str = Field(..., description="The type of developer i.e. Backend Dev, Frontend Dev, DevOps")


class TimelineTable(BaseModel):
    phase: str = Field(..., description="The phase title")
    features: list[Feature] = Field(..., description="The features to be covered in this phase.")
    duration: str = Field(..., description="The duration to complete this phase.")
    resources: list[Resource] = Field(..., description="The resources required in this phase")


class ResourceTable(BaseModel):
    developer: Resource = Field(..., description="The type of developer i.e. Backend Dev, Frontend Dev, DevOps")
    count: str = Field(..., description="The number of this type of developer")


class TimeLineModel(BaseModel):
    table: list[TimelineTable] = Field(..., description="A list of modules and actions for a timeline")
    resources: list[ResourceTable] = Field(..., description="A list if resource required for the project.")
    project_duration: str = Field(..., description="Overall project duration in work-days, including buffers")
    summary: str = Field(..., description="The brief summary of the proposed project timeline.")


class NonFunctionalRequirements(BaseModel):
    quality_assurance: str = Field(..., description="The quality assurance for the project.")
    risk_management: str = Field(..., description="The risk management for the project.")
    compliance: str = Field(..., description="The compliance for the project.")
    execution_methodology: str = Field(..., description="The execution methodology for the project.")
    testing: str = Field(..., description="The testing plan and execution.")
    training_plan: str = Field(..., description="The training plan for the project.")
    support_and_maintenance: str = Field(..., description="The support and maintenance for the project.")